# Change these first
owner: dhlee-dareesoft
repo: upptime

sites:
#  - name: 김천 WEB
#    url: https://public.riaas.ai
#    maxResponseTime: 3000
#  - name: 김천 API
#    url: https://public.riaas.ai/api/v2/customers/1
#    maxResponseTime: 3000
#  - name: 광주 WEB
#    url: https://gwangju.riaas.ai
#    maxResponseTime: 3000
#  - name: 광주 API
#    url: https://gwangju.riaas.ai/api/v2/customers/1
#    maxResponseTime: 3000
  - name: 구독 WEB
    url: https://korea.riaas.ai
    maxResponseTime: 3000
  - name: 구독 API
    url: https://korea.riaas.ai/api/v2/customers/1
    maxResponseTime: 3000
  - name : redact
    url : http://35.222.58.120:8787/services/v3/status
    maxResponseTime: 3000
  - name : prestd
    url : https://korea.riaas.ai/prest/schemas
    maxResponseTime: 3000

status-website:
  #cname: dhlee-dareesoft.github.io/upptime
  baseUrl: /upptime
  name: upptime
