# Change these first
owner: dhlee-dareesoft
repo: upptime

sites:
  - name: 김천
    url: $GIMCHEON_URL
    maxResponseTime: 3000
  - name: 광주
    url: $GWANGJU_URL
    maxResponseTime: 3000
  - name: 구독
    url: $KOREA_URL
    maxResponseTime: 3000

status-website:
  #cname: dhlee-dareesoft.github.io/upptime
  baseUrl: /upptime
  name: Upptime
