# Change these first
owner: dhlee-dareesoft
repo: upptime

sites:
  - name: 김천
    url: https://public.riaas.ai/api/v2/ping/dhlee
    maxResponseTime: 3000
  - name: 광주
    url: https://gwangju.riaas.ai/api/v2/ping/dhlee
    maxResponseTime: 3000
  - name: 구독
    url: https://korea.riaas.ai/api/v2/ping/dhlee
    maxResponseTime: 3000

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  name: Upptime
